-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 11:46:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kalender_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kalender_dim` (
  `KalenderDato` DATE NOT NULL,
  `Dag` INT NOT NULL,
  `Uge` INT NOT NULL,
  `Måned` INT NOT NULL,
  `År` INT NOT NULL,
  PRIMARY KEY (`KalenderDato`),
  UNIQUE INDEX `KalenderID_UNIQUE` (`KalenderDato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person_dim` (
  `PersonID` INT NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  `Telefon` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PersonID`),
  UNIQUE INDEX `BrugerID_UNIQUE` (`PersonID` ASC) VISIBLE,
  UNIQUE INDEX `Telefon_UNIQUE` (`Telefon` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tid_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tid_dim` (
  `TidID` TIME NOT NULL,
  `Time` INT NOT NULL,
  `Minut` INT NOT NULL,
  PRIMARY KEY (`TidID`),
  UNIQUE INDEX `TidID_UNIQUE` (`TidID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gentagelse_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gentagelse_dim` (
  `GentagelseID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL DEFAULT 'ugentligt' COMMENT 'dagligt, ugentligt, månedligt',
  `Frekvens` INT NOT NULL,
  `SlutDato` DATETIME NULL,
  PRIMARY KEY (`GentagelseID`),
  UNIQUE INDEX `GentagelseID_UNIQUE` (`GentagelseID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sted_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sted_dim` (
  `StedID` INT NOT NULL,
  `Online` BIT NOT NULL,
  `Lokale` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  `Kapacitet` INT NULL,
  PRIMARY KEY (`StedID`),
  UNIQUE INDEX `LokalID_UNIQUE` (`StedID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aftale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aftale` (
  `AftaleID` INT NOT NULL,
  `Titel` VARCHAR(45) NOT NULL DEFAULT '\Aftale\',
  `Beskrivelse` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NOT NULL DEFAULT 'aktiv' COMMENT 'aktiv, slettet, flyttet, bekræftet',
  `fk_EjerID` INT NOT NULL,
  `fk_StedID` INT NOT NULL,
  `fk_Start_KalenderDato` DATE NOT NULL,
  `fk_Slut_KalenderDato` DATE NOT NULL,
  `fk_Start_TidID` TIME NOT NULL,
  `fk_Slut_TidID` TIME NOT NULL,
  `fk_GentagelseID` INT NOT NULL,
  PRIMARY KEY (`AftaleID`, `fk_EjerID`, `fk_StedID`, `fk_Start_KalenderDato`, `fk_Slut_KalenderDato`, `fk_Start_TidID`, `fk_Slut_TidID`, `fk_GentagelseID`),
  UNIQUE INDEX `AftaleID_UNIQUE` (`AftaleID` ASC) VISIBLE,
  INDEX `fk_Aftale_Person_dim2_idx` (`fk_EjerID` ASC) VISIBLE,
  INDEX `fk_Aftale_Kalender_dim1_idx` (`fk_Start_KalenderDato` ASC) VISIBLE,
  INDEX `fk_Aftale_Kalender_dim2_idx` (`fk_Slut_KalenderDato` ASC) VISIBLE,
  INDEX `fk_Aftale_Tid_dim1_idx` (`fk_Start_TidID` ASC) VISIBLE,
  INDEX `fk_Aftale_Tid_dim2_idx` (`fk_Slut_TidID` ASC) VISIBLE,
  INDEX `fk_Aftale_Gentagelse1_idx` (`fk_GentagelseID` ASC) VISIBLE,
  INDEX `fk_Aftale_Sted_dim1_idx` (`fk_StedID` ASC) VISIBLE,
  CONSTRAINT `fk_Aftale_Person_dim2`
    FOREIGN KEY (`fk_EjerID`)
    REFERENCES `mydb`.`Person_dim` (`PersonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aftale_Kalender_dim1`
    FOREIGN KEY (`fk_Start_KalenderDato`)
    REFERENCES `mydb`.`Kalender_dim` (`KalenderDato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aftale_Kalender_dim2`
    FOREIGN KEY (`fk_Slut_KalenderDato`)
    REFERENCES `mydb`.`Kalender_dim` (`KalenderDato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aftale_Tid_dim1`
    FOREIGN KEY (`fk_Start_TidID`)
    REFERENCES `mydb`.`Tid_dim` (`TidID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aftale_Tid_dim2`
    FOREIGN KEY (`fk_Slut_TidID`)
    REFERENCES `mydb`.`Tid_dim` (`TidID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aftale_Gentagelse1`
    FOREIGN KEY (`fk_GentagelseID`)
    REFERENCES `mydb`.`Gentagelse_dim` (`GentagelseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aftale_Sted_dim1`
    FOREIGN KEY (`fk_StedID`)
    REFERENCES `mydb`.`Sted_dim` (`StedID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Undtagelse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Undtagelse` (
  `UndtagelseID` INT NOT NULL,
  `fk_GentagelseID` INT NOT NULL,
  `ForekomstDato` DATETIME NOT NULL,
  `Nydato` DATETIME NOT NULL,
  `Status` VARCHAR(45) NOT NULL COMMENT 'aktiv, slettet, flyttet, bekræftet',
  PRIMARY KEY (`UndtagelseID`),
  UNIQUE INDEX `UndtagelseID_UNIQUE` (`UndtagelseID` ASC) VISIBLE,
  INDEX `fk_Undtagelse_Gentagelse1_idx` (`fk_GentagelseID` ASC) VISIBLE,
  CONSTRAINT `fk_Undtagelse_Gentagelse1`
    FOREIGN KEY (`fk_GentagelseID`)
    REFERENCES `mydb`.`Gentagelse_dim` (`GentagelseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deltager_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deltager_bridge` (
  `DeltagerID` INT NOT NULL,
  `AftaleID` INT NOT NULL,
  PRIMARY KEY (`DeltagerID`, `AftaleID`),
  INDEX `fk_Person_dim_has_Aftale_Aftale1_idx` (`AftaleID` ASC) VISIBLE,
  INDEX `fk_Person_dim_has_Aftale_Person_dim1_idx` (`DeltagerID` ASC) VISIBLE,
  CONSTRAINT `fk_Person_dim_has_Aftale_Person_dim1`
    FOREIGN KEY (`DeltagerID`)
    REFERENCES `mydb`.`Person_dim` (`PersonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_dim_has_Aftale_Aftale1`
    FOREIGN KEY (`AftaleID`)
    REFERENCES `mydb`.`Aftale` (`AftaleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
